### ISSUE TITLE
Does VID training use 86G data?

### ISSUE THREAD

**Issue by xiaoxiaohahahaha** [foolwood/DCFNet#11]
Hello, does the training data use VID's latest 86G training? Why do I get out of memory errors when running train_DCFNet.m?

**Comment by foolwood** [comment]
We use the 86G training data in  http://bvisionweb1.cs.unc.edu/ilsvrc2015/download-videos-3j16.php#vid

We put **all the crop in memory**. (About **20G** RAM) to speed up the training process. 

If your PC ram is 8G, I suggest that you can set a small value in https://github.com/foolwood/DCFNet/blob/97d2cd784d9c2b1083c1249a2aef914062fb5910/training/getImdbDCFNet.m#L21

and use a subset of VID (n_videos =1000).

https://github.com/foolwood/DCFNet/blob/97d2cd784d9c2b1083c1249a2aef914062fb5910/training/getImdbDCFNet.m#L41


I will fix this problem on April.

**Comment by foolwood** [comment]
You can try the PyTorch  implementation.  
https://github.com/foolwood/DCFNet_pytorch

It's much faster and use less RAM.
You can train it on a PC with 8G RAM and a cheap GTX1060 in one day.
