### ISSUE TITLE
Is it possible to use stride in the network, how would it impact the tracking performance?

### ISSUE THREAD

**Issue by xiaofeiwu** [foolwood/DCFNet#14]

**Comment by foolwood** [comment]
Sorry for such a late reply.

I have try to use different input resolution. (169/125/63/33) SPCNet is a variant of DCFNet.
The accuracy performance will decrease with small resolution.

![image](https://user-images.githubusercontent.com/11716717/39982805-153b8b78-5788-11e8-9cbb-ccfbd5a96260.png)

I think the resolution (of feature maps) is really important.

**Comment by xiaofeiwu** [comment]
Thanks, the information is quite useful.
