### ISSUE TITLE
training process question

### ISSUE THREAD

**Issue by 522545707** [foolwood/DCFNet#15]
Hello,when I run the train_DCFNet.m,the display content in command window is like this:

train: epoch 08: 226/572: 84.8 (84.8) HZ objective:  44.632
train: epoch 08: 227/572: 84.8 (84.8) HZ objective:  44.628
train: epoch 08: 228/572: 84.8 (84.8) HZ objective:  44.549
train: epoch 08: 229/572: 84.8 (84.8) HZ objective:  44.570
......

the last value are always between 44 and 46,no obvious increase or decrease,I am not sure is it normal?
I use a subset of VID,the first 100 files in the first folder.

Thanks for your attention.

**Comment by foolwood** [comment]
Sorry for such late reply.
Maybe the subset is too small.  The objectives should below 10.
You can use the whole training set with less RAM via the PyTorch implementation. 
https://github.com/foolwood/DCFNet_pytorch
