### ISSUE TITLE
请问公式9和10的推导过程？~~~

### ISSUE THREAD

**Issue by OuYag** [foolwood/DCFNet#2]
thankyou~~~

**Comment by HakaseH** [comment]
First, we have
![image](https://cloud.githubusercontent.com/assets/14851451/25092478/85fec49e-23c0-11e7-9c7e-9cacea02f38a.png)

Then, we treat x and x* as independent variables.

The gradient of x can be obtained by
![image](https://cloud.githubusercontent.com/assets/14851451/25092586/f138064e-23c0-11e7-9a3d-8f4bda845735.png)

Similarly, the gradient of x* can derive by
![image](https://cloud.githubusercontent.com/assets/14851451/25092638/2b267ff2-23c1-11e7-9db1-456e2c35ebc9.png)
