### ISSUE TITLE
Missing definition for variables or function and file

### ISSUE THREAD

**Issue by stoneyang** [foolwood/DCFNet#4]
Hi, there:

U guys did a good job and thanks for sharing the code! 

When I tried to replicate your work done in the preprint, I've encountered two issues: 

1. When loading UAV123, the variable (or a function?) named `configSeqs` is not defined when it is called at [this line](https://github.com/foolwood/DCFNet/blob/master/training/getImdbRAM.m#L175). 

2. When loading NUS_PRO, the file named `seq_list_with_gt.csv` is non-exist in this repo as mentioned at [this line](https://github.com/foolwood/DCFNet/blob/master/training/getImdbRAM.m#L86).

The two issues blocked us from following your paper, ie, to train the DCFNet on the three datasets. 
So, could you please check them out and fix'em? 

@foolwood

Thanks.

**Comment by foolwood** [comment]
I feel sorry for the such a late reply.

I download the **configSeqs** and **seq_list_with_gt.csv** file in the two benchmark. 

You can download in this link: 
https://pan.baidu.com/s/1hr8xdJm
passwd: 9jwb

Great thanks for your attention about DCFNet. The official paper is not accepted, and I will make a big update (both in accuracy and speed) after acceptance.

**Comment by stoneyang** [comment]
@foolwood thanks for your reply and for sharing the data.
